first = input('Input your First Number\n')
second = input('Input your Second Number\n')
third = input('Input your Third Number\n')
fourth = input('Input your Fourth Number\n')
fifth = input('Input your Fifth Number\n')
print('Float of %s Equal'%first,float(first))
print('Complex of %s Equal'%first,complex(first))
print('Float of %s Equal'%second,float(second))
print('Complex of %s Equal'%second,complex(second))
print('Float of %s Equal'%third,float(third))
print('Complex of %s Equal'%third,complex(third))
print('Float of %s Equal'%fourth,float(fourth))
print('Complex of %s Equal'%fourth,complex(fourth))
print('Float of %s Equal'%fifth,float(fifth))
print('Complex of %s Equal'%fifth,complex(fifth))